### ISSUE TITLE
Uncaught TypeError: Cannot read property 'digest' of undefined

### ISSUE THREAD

**Issue by burakbuylu** [pheditor/pheditor#44] opened 2021-02-04 19:55 UTC
Uncaught TypeError: Cannot read property 'digest' of undefined
    at sha512 (editor.php:225)
    at editor.php:525
    at dispatch (jquery.js:5183)
    at elemData.handle (jquery.js:4991)
    at Object.trigger (jquery.js:8249)
    at jquery.js:8327
    at Function.each (jquery.js:354)
    at jQuery.fn.init.each (jquery.js:189)
    at jQuery.fn.init.trigger (jquery.js:8326)
    at HTMLDocument.<anonymous> (editor.php:588)

**Comment by hamidsamak** [comment] 2021-02-05 05:07
Duplicate of #35

**Closed** 2021-02-05 05:08 UTC
